services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: python-backend
    restart: unless-stopped
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - /:/hostfs:ro
      - /sys:/sys:ro
    environment:
      - PORT=8000